# Generated by Django 3.0.3 on 2020-03-01 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200301_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
