# Generated by Django 3.0.3 on 2020-03-02 12:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20200301_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=400)),
                ('imagefile', models.FileField(null=True, upload_to='images')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='reviews',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
